# Configuración del build
[build]
  command = "npm run build"
  publish = "dist/frontend"

# Regla de redirección para enrutamiento SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
